AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    Url Shortener Service
    
Globals:
    Function:
        Timeout: 3

Resources:
    GetShortUrlEndpoint:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: builds/get_short_url.zip
            Handler: app.handler
            Policies: AmazonDynamoDBFullAccess
            Runtime: python3.6
            Events:
                GetShortUrl:
                    Type: Api
                    Properties:
                        Path: /{linkId}
                        Method: get
    UrlTable:
        Type: AWS::DynamoDB::Table
        Properties: 
        AttributeDefinitions: 
            - AttributeName: id
              AttributeType: S
            - AttributeName: longUrl
              AttributeType: S
        KeySchema: 
            - AttributeName: id
              KeyType: HASH
            - AttributeName: longUrl
              KeyType: RANGE
        ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

Outputs:
    GetShortUrlApi:
      Description: "API Gateway endpoint URL for Prod stage for the function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"